notify when attempting to use ssh but user is member of group ssh

diff --git a/usr/lib/security-misc/pam_tally2-info b/usr/lib/security-misc/pam_tally2-info
--- a/usr/lib/security-misc/pam_tally2-info
+++ b/usr/lib/security-misc/pam_tally2-info
@@ -3,8 +3,31 @@
 ## Copyright (C) 2019 - 2019 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
 ## See the file COPYING for copying conditions.
 
-## https://forums.whonix.org/t/etc-security-hardening-console-lockdown/8592
-if grep -q "accessfile=/etc/security/access-security-misc.conf" /etc/pam.d/common-account 2>/dev/null; then
+grep_result="$(grep "accessfile=/etc/security/access-security-misc.conf" /etc/pam.d/common-account 2>/dev/null)"
+
+if ! echo "$grep_result" | grep -q "#" ; then
+   ## https://forums.whonix.org/t/etc-security-hardening-console-lockdown/8592
+
+   if [ "$PAM_SERVICE" = "sshd" ]; then
+      if id --name --groups --zero "$PAM_USER" | grep --quiet --null-data --line-regexp --fixed-strings "ssh"; then
+         ssh_allowed=true
+      fi
+      if [ ! "$ssh_allowed" = "true" ]; then
+         echo "$0: ERROR: PAM_USER: $PAM_USER is not a member of group 'ssh'" >&2
+         echo "$0: To unlock, run the following command as superuser:" >&2
+         echo "$0: (If you still have a sudo/root shell somewhere.)" >&2
+         echo "" >&2
+         echo "addgroup $PAM_USER ssh" >&2
+         echo "" >&2
+         echo "$0: However, possibly unlock procedure is required." >&2
+         echo "$0: First boot into recovery mode at grub boot menu and then run above command." >&2
+         echo "$0: See also:" >&2
+         echo "https://www.whonix.org/wiki/root#ssh" >&2
+         echo "" >&2
+         exit 0
+      fi
+   fi
+
    if id --name --groups --zero "$PAM_USER" | grep --quiet --null-data --line-regexp --fixed-strings "console"; then
       console_allowed=true
    fi
