output

diff --git a/usr/lib/security-misc/permission-hardening b/usr/lib/security-misc/permission-hardening
--- a/usr/lib/security-misc/permission-hardening
+++ b/usr/lib/security-misc/permission-hardening
@@ -262,4 +262,8 @@ parse_config_folder() {
 
 parse_config_folder
 
+if [ ! "$exit_code" = "0" ]; then
+   echo "ERROR: Will exist with non-zero exit code: '$exit_code'" >&2
+fi
+
 exit "$exit_code"
