use read (built-in) rather than awk (external)

diff --git a/usr/lib/security-misc/permission-hardening b/usr/lib/security-misc/permission-hardening
--- a/usr/lib/security-misc/permission-hardening
+++ b/usr/lib/security-misc/permission-hardening
@@ -6,11 +6,10 @@ set_file_perms() {
   while read -r line; do
     [[ "$line" =~ ^#.*$ ]] && continue
 
-    file="$(awk '{print $1}' <<< ${line})"
-    mode="$(awk '{print $2}' <<< ${line})"
-    owner="$(awk '{print $3}' <<< ${line})"
-    group="$(awk '{print $4}' <<< ${line})"
-    capability="$(awk '{print $5}' <<< ${line})"
+    if ! read -r file mode owner group capability <<< "${line}" ; then
+      echo "ERROR: cannot parse line: ${line}"
+      continue
+    fi
 
     if ! [ -e "${file}" ]; then
       echo "ERROR: File '${file}' does not exist!"
