output

diff --git a/usr/lib/security-misc/permission-hardening b/usr/lib/security-misc/permission-hardening
--- a/usr/lib/security-misc/permission-hardening
+++ b/usr/lib/security-misc/permission-hardening
@@ -19,6 +19,7 @@ echo_wrapper() {
 add_nosuid_statoverride_entry() {
   while read -r line; do
     if ! read -r file_name existing_mode owner group; then
+      echo "ERROR: cannot parse line by 'stat' - line: '$line'" >&2
       continue
     fi
 
