debian: use debconf to prompt questions BROKEN! db_get returns nothing to $RET :(

diff --git a/debian/security-misc.preinst b/debian/security-misc.preinst
--- a/debian/security-misc.preinst
+++ b/debian/security-misc.preinst
@@ -3,6 +3,9 @@
 ## Copyright (C) 2012 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
 ## See the file COPYING for copying conditions.
 
+## Source debconf lib
+. /usr/share/debconf/confmodule
+
 if [ -f /usr/lib/helper-scripts/pre.bsh ]; then
    source /usr/lib/helper-scripts/pre.bsh
 fi
@@ -94,6 +97,7 @@ sudo_users_check () {
    ## Prevent users from locking themselves out.
    ## https://forums.whonix.org/t/is-security-misc-suitable-for-hardening-bridges-and-relays/8299/4
 <<<<<<< HEAD
+<<<<<<< HEAD
    echo "$0: ERROR: No user is a member of group 'sudo'. Installation aborted." >&2
    echo "$0: ERROR: You probably want to run:" >&2
    echo "" >&2
@@ -114,24 +118,23 @@ sudo_users_check () {
 
    exit 200
 =======
+=======
+   add_current_user_to_sudo=no
+>>>>>>> debian: use debconf to prompt questions
    if [ ! "$are_there_any_sudo_users" = "yes" ]; then
       echo "$0: ERROR: No user is a member of group 'sudo'." >&2
-      echo "$0: Do you want to add current user $USER to 'sudo' group?" >&2
-      read -r input
+      db_get security-misc/add_user_to_sudo || true
 
-      case $input in
-         [yY][eE][sS]|[yY])
-       add_current_user_to_sudo=1
-       ;;
-         [nN][oO]|[nN])
-       add_current_user_to_sudo=0
-       ;;
-         *)
-       echo "$0: ERROR: Invalid input, aborting" >&2
-       exit 200
-       ;;
-      esac
+      echo "RET VALUE: $RET" >&2
+      if [ "$RET" = "true" ]; then 
+          add_current_user_to_sudo=yes
+      else 
+          echo "$0: ERROR: Invalid input, aborting" >&2
+	  exit 200
+      fi
    fi
+
+   echo "DEBUG: $add_current_user_to_sudo" >&2
    
    if [ ! "$add_current_user_to_sudo" == "yes" ]; then
       echo "$0: ERROR: You probably want to run:" >&2
@@ -189,6 +192,7 @@ console_users_check() {
    ## Prevent users from locking themselves out.
    ## https://forums.whonix.org/t/is-security-misc-suitable-for-hardening-bridges-and-relays/8299/4
 <<<<<<< HEAD
+<<<<<<< HEAD
    if [ "$are_there_any_console_users" = "yes" ]; then
       return 0
    fi
@@ -205,23 +209,19 @@ console_users_check() {
       output_skip_checks "Environment variable SECURITY_MISC_INSTALL is set to 'force'."
       return 0
 =======
+=======
+   add_current_user_to_console=no
+>>>>>>> debian: use debconf to prompt questions
    if [ ! "$are_there_any_console_users" = "yes" ]; then
       echo "$0: ERROR: No user is a member of group 'console'" >&2
-      echo "$0: Do you want to add current user $USER to 'console' group?" >&2
-      read -r input
+      db_get security-misc/add_user_to_console || true
 
-      case $input in
-         [yY][eE][sS]|[yY])
-       add_current_user_to_console=1
-       ;;
-         [nN][oO]|[nN])
-       add_current_user_to_console=0
-       ;;
-         *)
+      if [ "$RET" = "true" ]
+      then add_current_user_to_console=yes
+      else 
        echo "$0: ERROR: Invalid input, aborting" >&2
        exit 200
-       ;;
-      esac
+      fi
    fi
 
    if [ ! "$add_current_user_to_console" == "yes" ]; then
@@ -291,7 +291,6 @@ if [ "$1" = "install" ] || [ "$1" = "upgrade" ]; then
    sudo_users_check
    console_users_check
 fi
-
 true "INFO: debhelper beginning here."
 
 #DEBHELPER#
