Make the main field count check in permission-hardener a bit more elegant

diff --git a/usr/bin/permission-hardener b/usr/bin/permission-hardener
--- a/usr/bin/permission-hardener
+++ b/usr/bin/permission-hardener
@@ -410,13 +410,14 @@ load_state() {
 
       IFS=' ' read -r -a field_list <<< "${line}"
 
-      if (( ${#field_list[@]} != 2 )) \
-        && (( ${#field_list[@]} != 4 )) \
-        && (( ${#field_list[@]} != 5 )); then
-        exit_code=200
-        log error "Line contains an invalid number of fields: '${line}'" >&2
-        exit "${exit_code}"
-      fi
+      case "${#field_list[@]}" in
+        2|4|5) true;;
+        *)
+          exit_code=200
+          log error "Line contains an invalid number of fields: '${line}'" >&2
+          exit "${exit_code}"
+          ;;
+      esac
 
       # Strip trailing slash if appropriate
       field_list[0]="${field_list[0]%/}"
